PostgresDB:
  user: 'postgres'
  password: 'password'
  host: 'database'
  port: '5432'
  dbname: 'postgres'
  sslmode: 'disable'
  maxconns: '30'
  
Server:
  bindAddr: '0.0.0.0:8000'
  readTimeout: '10'
  writeTimeout: '10'
  idleTimeout: '5'